#!/usr/bin/env bash

echo "prepare..."
rm -rf dist
mkdir -p dist
rm -rf .built
mkdir -p .built

echo "building qs.ls -> qs.js ..."
./node_modules/.bin/lsc -cp --no-header src/qs.ls > dist/qs.js
echo "minify qs.js -> qs.min.js ..."
./node_modules/.bin/uglifyjs dist/qs.js -c -m > dist/qs.min.js
echo "building datefmt.ls -> datefmt.js ..."
./node_modules/.bin/lsc -cp --no-header src/datefmt.ls > dist/datefmt.js

echo "building cookie.ls -> cookie.js ..."
./node_modules/.bin/lsc -cp --no-header src/cookie.ls > dist/cookie.js
echo "minify cookie.js -> cookie.min.js ..."
./node_modules/.bin/uglifyjs dist/cookie.js -c -m > dist/cookie.min.js

echo "building index.ls -> index.js ..."
cp dist/* .built
./node_modules/.bin/lsc -cp --no-header src/index.ls > .built/index.js

echo "bundling index.js ..."
./node_modules/.bin/browserify -s httputil .built/index.js > dist/index.js
echo "minify bundled index.js -> index.min.js ..."
./node_modules/.bin/uglifyjs dist/index.js -c -m > dist/index.min.js

echo "copy dist to web ..."
rm -rf web/static/assets/lib/@plotdb/httputil/dev/
mkdir -p web/static/assets/lib/@plotdb/httputil/dev/
cp -R dist/* web/static/assets/lib/@plotdb/httputil/dev/
rm -rf .built
